<a href="https://colab.research.google.com/github/shimmer02/CODSOFT/blob/main/churn.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [111]:
import pandas as pd
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from matplotlib import pyplot as plt
from sklearn.model_selection import train_test_split

Reading the CSV file

In [ ]:
churn = pd.read_csv('/content/Churn_Modelling.csv')

In [ ]:
churn.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [ ]:
churn['Geography']

0        France
1         Spain
2        France
3        France
4         Spain
         ...
9995     France
9996     France
9997     France
9998    Germany
9999     France
Name: Geography, Length: 10000, dtype: object

In [ ]:
churn.corr()

<ipython-input-24-9f285b74dfe6>:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  churn.corr()

,RowNumber,CustomerId,CreditScore,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
RowNumber,1.000000,0.004202,0.005840,0.000783,-0.006495,-0.009067,0.007246,0.000599,0.012044,-0.005988,-0.016571
CustomerId,0.004202,1.000000,0.005308,0.009497,-0.014883,-0.012419,0.016972,-0.014025,0.001665,0.015271,-0.006248
CreditScore,0.005840,0.005308,1.000000,-0.003965,0.000842,0.006268,0.012238,-0.005458,0.025651,-0.001384,-0.027094
Age,0.000783,0.009497,-0.003965,1.000000,-0.009997,0.028308,-0.030680,-0.011721,0.085472,-0.007201,0.285323
Tenure,-0.006495,-0.014883,0.000842,-0.009997,1.000000,-0.012254,0.013444,0.022583,-0.028362,0.007784,-0.014001
Balance,-0.009067,-0.012419,0.006268,0.028308,-0.012254,1.000000,-0.304180,-0.014858,-0.010084,0.012797,0.118533
NumOfProducts,0.007246,0.016972,0.012238,-0.030680,0.013444,-0.304180,1.000000,0.003183,0.009612,0.014204,-0.047820
HasCrCard,0.000599,-0.014025,-0.005458,-0.011721,0.022583,-0.014858,0.003183,1.000000,-0.011866,-0.009933,-0.007138
IsActiveMember,0.012044,0.001665,0.025651,0.085472,-0.028362,-0.010084,0.009612,-0.011866,1.000000,-0.011421,-0.156128
EstimatedSalary,-0.005988,0.015271,-0.001384,-0.007201,0.007784,0.012797,0.014204,-0.009933,-0.011421,1.000000,0.012097
Exited,-0.016571,-0.006248,-0.027094,0.285323,-0.014001,0.118533,-0.047820,-0.007138,-0.156128,0.012097,1.000000

In [97]:
churnx = churn.drop('Exited', axis = 1)

In [98]:
churnx.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [99]:
churnx = churnx.drop('RowNumber', axis = 1)
churnx = churnx.drop('CustomerId', axis = 1)
churnx = churnx.drop('Surname', axis = 1)

In [100]:
churnx.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,619,France,Female,42,2,0.00,1,1,1,101348.88
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58
2,502,France,Female,42,8,159660.80,3,1,0,113931.57
3,699,France,Female,39,1,0.00,2,0,0,93826.63
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10

In [101]:
churny = churn[['Exited']]

In [102]:
churny.head()

   Exited
0       1
1       0
2       1
3       0
4       0

In [103]:
churnx = churnx.drop('Geography', axis = 1)

In [124]:
churnx['CreditScore'] = churnx['CreditScore']/850
churnx['Age'] = churnx['Age']/92
churnx['Tenure'] = churnx['Tenure']/10
churnx['Balance'] = churnx['Balance']/250898.090000
churnx['EstimatedSalary'] = churnx['EstimatedSalary']/199992.480000

In [125]:
churnx.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0.728235,0,0.456522,0.2,0.000000,1,1,1,0.506763
1,0.715294,0,0.445652,0.1,0.334031,1,0,1,0.562734
2,0.590588,0,0.456522,0.8,0.636357,3,1,0,0.569679
3,0.822353,0,0.423913,0.1,0.000000,2,0,0,0.469151
4,1.000000,0,0.467391,0.2,0.500246,1,1,1,0.395435

In [126]:
churnx['Gender'].replace({'Male': 1 }, inplace = True)

In [127]:
churnx.describe()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
count,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.000000,10000.00000,10000.000000,10000.000000
mean,0.765328,0.545700,0.423063,0.501280,0.304848,1.530200,0.70550,0.515100,0.500470
std,0.113710,0.497932,0.113998,0.289217,0.248696,0.581654,0.45584,0.499797,0.287563
min,0.411765,0.000000,0.195652,0.000000,0.000000,1.000000,0.00000,0.000000,0.000058
25%,0.687059,0.000000,0.347826,0.300000,0.000000,1.000000,0.00000,0.000000,0.255020
50%,0.767059,1.000000,0.402174,0.500000,0.387402,1.000000,1.00000,1.000000,0.500988
75%,0.844706,1.000000,0.478261,0.700000,0.508749,2.000000,1.00000,1.000000,0.746969
max,1.000000,1.000000,1.000000,1.000000,1.000000,4.000000,1.00000,1.000000,1.000000

In [128]:
churnx.tail()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
9995,0.907059,1,0.423913,0.5,0.000000,2,1,0,0.481371
9996,0.607059,1,0.380435,1.0,0.228657,1,1,1,0.508518
9997,0.834118,0,0.391304,0.7,0.000000,1,0,1,0.210436
9998,0.908235,1,0.456522,0.3,0.299226,2,1,0,0.464460
9999,0.931765,0,0.304348,0.4,0.518708,1,1,0,0.190961

In [129]:
churnx['Gender'].replace({'Female': 0}, inplace = True)

In [130]:
churnx.tail()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
9995,0.907059,1,0.423913,0.5,0.000000,2,1,0,0.481371
9996,0.607059,1,0.380435,1.0,0.228657,1,1,1,0.508518
9997,0.834118,0,0.391304,0.7,0.000000,1,0,1,0.210436
9998,0.908235,1,0.456522,0.3,0.299226,2,1,0,0.464460
9999,0.931765,0,0.304348,0.4,0.518708,1,1,0,0.190961

In [131]:
churnx.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0.728235,0,0.456522,0.2,0.000000,1,1,1,0.506763
1,0.715294,0,0.445652,0.1,0.334031,1,0,1,0.562734
2,0.590588,0,0.456522,0.8,0.636357,3,1,0,0.569679
3,0.822353,0,0.423913,0.1,0.000000,2,0,0,0.469151
4,1.000000,0,0.467391,0.2,0.500246,1,1,1,0.395435

In [132]:
X_train, X_test, Y_train, Y_test = train_test_split(churnx, churny, random_state = 2, stratify = churny, test_size = 0.2)

In [133]:
X_train.shape

(8000, 9)

In [134]:
X_test.shape

(2000, 9)

In [135]:
classifier = LogisticRegression()

In [136]:
classifier.fit(X_train, Y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/utils/validation.py:1143: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

LogisticRegression()

In [139]:
churn_pred = classifier.predict(X_test)
accuracy = accuracy_score(churn_pred, Y_test)

In [140]:
accuracy

0.8005

In [141]:
churnx.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary
0,0.728235,0,0.456522,0.2,0.000000,1,1,1,0.506763
1,0.715294,0,0.445652,0.1,0.334031,1,0,1,0.562734
2,0.590588,0,0.456522,0.8,0.636357,3,1,0,0.569679
3,0.822353,0,0.423913,0.1,0.000000,2,0,0,0.469151
4,1.000000,0,0.467391,0.2,0.500246,1,1,1,0.395435

In [145]:
input = (1.000000,	0,	0.467391,	0.2,	0.500246,	1,	1,	1,	0.395435)
npin = np.asarray(input)
rs = npin.reshape(1, -1)
churn_pred = classifier.predict(rs)

churn_pred

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])